=== EuPathDB-Infra/GusAppFramework/Community/config/FileTranslatorCfg.dtd
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!-- 

FileTranslatorCfg.dtd 

A DTD specification for configuration files 
that map one tab-delim format to another.

Author: Angel Pizarro

$Revision $ $Date $ $Author$ 

-->

<!ELEMENT cfg (inputs+, outputs+) >

<!ATTLIST cfg 
      functions_class CDATA #IMPLIED >

<!ELEMENT inputs (var*, header) > 
<!ATTLIST inputs 
    qualifier_row_present (0|1) "0" > 

<!ELEMENT header (col*)>

<!ELEMENT col EMPTY >
<!ATTLIST col
  name ID #REQUIRED
  header_val CDATA #REQUIRED
  req (0|1) "0" 
  qualifier (0|1) "0"
>

<!ELEMENT outputs (idmap?, map*) >

<!ELEMENT map (in*,do) >
<!ATTLIST map 
  name CDATA #REQUIRED 
>

<!ELEMENT idmap (in*) >

<!ATTLIST idmap
  output_header CDATA #REQUIRED
  function CDATA #REQUIRED 
  mapkey CDATA #REQUIRED
>

<!ELEMENT in EMPTY >

<!ATTLIST in
  name IDREF #REQUIRED
>

<!ELEMENT do (#PCDATA) >

=== EuPathDB-Infra/GusAppFramework/RAD/config/sample_BatchResultLoader_GenePix.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- $Revision$ $Date$ $Author$ -->

<cfg functions_class='GUS::RAD::FileTranslator::Functions'>
 <inputs qualifier_row_present='0'>
   <header >
    <col header_val='Block' req='1' name='block'/>
    <col header_val='Row' req='1' name='row'/>
    <col header_val='Column' req='1' name='column'/>
    <col header_val='F635 SD' name='r_f_sd' />
    <col header_val='B635 SD' name='r_b_sd'/>
    <col header_val='Dia.' name='diam'/>
    <col header_val='F635 Mean' name='r_f_mean'/>
    <col header_val='F635 Median' name='r_f_median'/>
    <col header_val='B635 Mean' name='r_b_mean'/>
    <col header_val='B635 Median' name='r_b_median'/>
    <col header_val='% > B635+1SD' name='r_perc_overb_plus1'/>
    <col header_val='% > B635+2SD' name='r_perc_overb_plus2'/>
    <col header_val='F635 % Sat.' name='r_perc_sat'/>
    <col header_val='Mean of Ratios' name='mean_of_ratios'/>
    <col header_val='Median of Ratios' name='median_of_ratios'/>
    <col header_val='Ratios SD' name='ratios_sd'/>
    <col header_val='Rgn Ratio' name='rgn_ratio'/>
    <col header_val='Rgn R²' name='rgn_rsq'/>
    <col header_val='F Pixels' name='f_pix'/>
    <col header_val='B Pixels' name='b_pix'/>
    <col header_val='Flags' name='flag'/>
    <col header_val='F532 SD' name='g_f_sd'/>
    <col header_val='B532 SD' name='g_b_sd'/>
    <col header_val='F532 Mean' name='g_f_mean'/>
    <col header_val='F532 Median' name='g_f_median'/>
    <col header_val='B532 Mean' name='g_b_mean'/>
    <col header_val='B532 Median' name='g_b_median'/>
    <col header_val='% > B532+1SD' name='g_perc_overb_plus1'/>
    <col header_val='% > B532+2SD' name='g_perc_overb_plus2'/>
    <col header_val='F532 % Sat.' name='g_perc_sat'/>
    <col header_val='Circularity' name='circularity'/>
    <col header_val='Autoflag' name='autoflag'/>
   </header>
 </inputs>

 <outputs>
    <idmap function='coordGenePix2RAD'
           output_header="array_row\tarray_column\tgrid_row\tgrid_column\tsub_row\tsub_column"
           mapkey='$block\t$row\t$column'  >
      <in name='block'/>
      <in name='row'/>
      <in name='column'/>
    </idmap>
    <map name='R.foreground_sd'> 
      <in name='r_f_sd'/>
      <do>$r_f_sd</do>
    </map>
    <map name='R.background_sd'> 
      <in name='r_b_sd'/>
      <do>$r_b_sd</do>
    </map>
    <map name='R.spot_diameter'>
      <in name='diam'/>
      <do>$diam</do>
     </map>
    <map name='R.foreground_mean'> 
      <in name='r_f_mean'/>
      <do>$r_f_mean</do>
    </map>
    <map name='R.foreground_median'>
      <in name='r_f_median'/>
      <do>$r_f_median</do>
    </map>
    <map name='R.background_mean'>
      <in name='r_b_mean'/>
      <do>$r_b_mean</do>
    </map>
    <map name='R.background_median'>
      <in name='r_b_median'/>
      <do>$r_b_median</do>
    </map>
    <map name='R.percent_over_bg_plus_one_sd'>
      <in name='r_perc_overb_plus1'/>
      <do>$r_perc_overb_plus1</do>
    </map>
    <map name='R.percent_over_bg_plus_two_sds'>
      <in name='r_perc_overb_plus2'/>
      <do>$r_perc_overb_plus2</do>
    </map>
    <map name='R.percent_foreground_saturated'>
      <in name='r_perc_sat'/>
      <do>$r_perc_sat</do>
    </map>
    <map name='R.mean_of_ratios'>
      <in name='mean_of_ratios'/>
      <do>$mean_of_ratios</do>
    </map>
    <map name='R.median_of_ratios'>
      <in name='median_of_ratios'/>
      <do>$median_of_ratios</do>
    </map>
    <map name='R.ratios_sd'>
      <in name='ratios_sd'/>
      <do>$ratios_sd</do>
    </map>
    <map name='R.rgn_ratio'>
      <in name='rgn_ratio'/>
      <do>$rgn_ratio</do>
    </map>
    <map name='R.rgn_r_squared'>
      <in name='rgn_rsq' />
      <do>$rgn_rsq</do>
    </map>
    <map name='R.num_foreground_pixels'>
      <in name='f_pix'/>
      <do>$f_pix</do>
    </map>
    <map name='R.num_background_pixels'>
      <in name='b_pix'/>
      <do>$b_pix</do>
    </map>
    <map name='R.flag'>
      <in name='flag'/>
      <do>$flag</do>
    </map>
    <map name='R.circularity'>
      <in name='circularity'/>
      <do>$circularity</do>
    </map>
    <map name='R.autoflag'>
      <in name='autoflag'/>
      <do>$autoflag</do>
    </map>
    <map name='G.foreground_sd'>
      <in name='g_f_sd'/>
      <do>$g_f_sd</do>
    </map>
    <map name='G.background_sd'>
      <in name='g_b_sd'/>
      <do>$g_b_sd</do>
    </map>
    <map name='G.spot_diameter'>
      <in name='diam'/>
      <do>$diam</do>
    </map>
    <map name='G.foreground_mean'>
      <in name='g_f_mean'/>
      <do>$g_f_mean</do>
    </map>
    <map name='G.foreground_median'>
      <in name='g_f_median'/>
      <do>$g_f_median</do>
    </map>
    <map name='G.background_mean'>
      <in name='g_b_mean'/>
      <do>$g_b_mean</do>
    </map>
    <map name='G.background_median'>
      <in name='g_b_median'/>
      <do>$g_b_median</do>
    </map>
    <map name='G.percent_over_bg_plus_one_sd'> 
      <in name='g_perc_overb_plus1'/>
      <do>$g_perc_overb_plus1</do>
    </map>
    <map name='G.percent_over_bg_plus_two_sds'>
      <in name='g_perc_overb_plus2'/>
      <do>$g_perc_overb_plus2</do>
    </map>
    <map name='G.percent_foreground_saturated'>
      <in name='g_perc_sat'/>
      <do>$g_perc_sat</do>
    </map>
    <map name='G.mean_of_ratios'>
      <in name='mean_of_ratios'/>
      <do>$mean_of_ratios</do>
    </map>
    <map name='G.median_of_ratios'>
      <in name='median_of_ratios'/>
      <do>$median_of_ratios</do>
    </map>
    <map name='G.ratios_sd'>
      <in name='ratios_sd'/>
      <do>$ratios_sd</do>
    </map>
    <map name='G.rgn_ratio'>
      <in name='rgn_ratio'/>
      <do>$rgn_ratio</do>
    </map>
    <map name='G.rgn_r_squared'>
      <in name='rgn_rsq'/>
      <do>$rgn_rsq</do>
    </map>
    <map name='G.num_foreground_pixels'>
      <in name='f_pix'/>
      <do>$f_pix</do>
    </map>
    <map name='G.num_background_pixels'>
      <in name='b_pix'/>
      <do> $b_pix </do>
    </map>
    <map name='G.flag'>
      <in name='flag'/>
      <do>$flag</do>
    </map>
    <map name='G.circularity'>
      <in name='circularity'/>
      <do>$circularity</do>
    </map>
    <map name='G.autoflag'>
      <in name='autoflag'/>
      <do>$autoflag</do>
    </map>
 </outputs>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_LoadBatchArrayResults_AffymetrixMAS4.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- $Revision$ $Date$ $Author$ -->

<cfg>
  <inputs qualifier_row_present='0'>
    <header>
      <col header_val ='Probe Set Name' req='1' name='probe_set_name' />
      <col header_val='Positive Pairs'  name='pos_pairs' />
      <col header_val='Negative Pairs'  name='neg_pairs' />
      <col header_val='Pairs Used'  name='pairs_used' />
      <col header_val='Pairs InAvg'  name='pairs_inavg' />
      <col header_val='Log Avg Pos/Neg'  req='1' name='log_avg_ratio' />
      <col header_val='Ave Diff'  req='1'  name='avg_diff' />
      <col header_val='Abs Call'  req='1' name='abs_call' />
    </header>
  </inputs>

  <outputs>
    <map name='name'>
      <in name='probe_set_name' />
      <do> $probe_set_name </do>
    </map>
    <map name='positive_probe_pairs'>
      <in name='pos_pairs' />
      <do> $pos_pairs </do>
    </map>
    <map name='negative_probe_pairs'>
      <in name='neg_pairs' />
      <do> $neg_pairs </do>
    </map>
     <map name='num_probe_pairs_used'>
      <in name='pairs_used' />
      <do> $pairs_used </do>
    </map>
    <map name='pairs_in_average'>
      <in name='pairs_inavg' />
      <do> $pairs_inavg </do>
    </map>
    <map name='log_average_ratio'>
      <in name='log_avg_ratio' />
      <do> $log_avg_ratio </do>
    </map>
    <map name='average_difference'>
      <in name='avg_diff' />
      <do> $avg_diff </do>
    </map>
    <map name='absolute_call'>
      <in name='abs_call' />
      <do> $abs_call </do>
    </map>
  </outputs>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_BatchResultLoader_ArrayVision2.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- 
 $Revision$ $Date$ $Author$
-->

<cfg>
 <inputs qualifier_row_present='1' > 
  <row  name='col_headers' >
    <col name='R.foreground' header_val='Dens - Levels' qualifier='0' req='1' />
    <col name='R.sd' header_val='SD - Levels' qualifier='0' req='0' />
    <col name='R.x' header_val='PosX - mm' qualifier='0' req='0' />
    <col name='R.y' header_val='PosY - mm' qualifier='0' req='0' />
    <col name='R.area' header_val='Area - mm2' qualifier='0' req='0' />
    <col name='R.bkgd' header_val='Bkgd' qualifier='0' req='0' />
    <col name='R.sn' header_val='S/N' qualifier='0' req='0' />
    <col name='R.flag' header_val='Flag' qualifier='0' req='0' />
    <col name='R.percent_floor' header_val='% At Floor' qualifier='0' req='0' />
    <col name='R.percent_ceiling' header_val='% At Ceiling' qualifier='0' req='0' />
    <col name='R.bg_percent_floor' header_val='% At Floor - Bkgd' qualifier='0' req='0' />
    <col name='R.bg_percent_ceiling' header_val='% At Ceiling - Bkgd' qualifier='0' req='0' />
    <col name='R.mad' header_val='MAD' qualifier='0' req='0' />
    <col name='R.percent_removed' header_val='% Removed' qualifier='0' req='0' />
    <col name='R.percent_replaced' header_val='% Replaced' qualifier='0' req='0' />
    <col name='G.foreground' header_val='Dens - Levels' qualifier='1' req='1' />
    <col name='G.sd' header_val='SD - Levels' qualifier='1' req='0' />
    <col name='G.x' header_val='PosX - mm' qualifier='1' req='0' />
    <col name='G.y' header_val='PosY - mm' qualifier='1' req='0' />
    <col name='G.area' header_val='Area - mm2' qualifier='1' req='0' />
    <col name='G.bkgd' header_val='Bkgd' qualifier='1' req='0' />
    <col name='G.sn' header_val='S/N' qualifier='1' req='0' />
    <col name='G.flag' header_val='Flag' qualifier='1' req='0' />
    <col name='G.percent_floor' header_val='% At Floor' qualifier='1' req='0' />
    <col name='G.percent_ceiling' header_val='% At Ceiling' qualifier='1' req='0' />
    <col name='G.bg_percent_floor' header_val='% At Floor - Bkgd' qualifier='1' req='0' />
    <col name='G.bg_percent_ceiling' header_val='% At Ceiling - Bkgd' qualifier='1' req='0' />
    <col name='G.mad' header_val='MAD' qualifier='1' req='0' />
    <col name='G.percent_removed' header_val='% Removed' qualifier='1' req='0' />
    <col name='G.percent_replaced' header_val='% Replaced' qualifier='1' req='0' />
  </row>
 </inputs>
 <outputs>
  <map name='coordinate' >
    <in col='coor' />
    <do> $coor </do>
  </map>   
  <map name='foreground' >
    <in col='R.foreground' />
    <do> $R.foreground </do>
  </map>
  <map name='background' >
    <in col='R.bkgd' />
    <do> $R.bkgd </do>
  </map>
  <map name='sd' >
    <in col='R.sd' />
    <do> $R.sd</do>
  </map>
  <map name='signal_to_noise' >
    <in col='R.sn' />
    <do> $R.sn</do>
  </map>
  <map name='percent_at_floor' >
    <in col='R.percent_floor' />
    <do> $R.percent_floor</do>
  </map>
  <map name='percent_at_ceiling' >
    <in col='R.percent_ceiling' />
    <do> $R.percent_ceiling</do>
  </map>
  <map name='bkg_percent_at_floor' >
    <in col='R.bg_percent_floor' />
    <do> $R.bg_percent_floor</do>
  </map>
  <map name='bg_percent_at_ceiling' >
    <in col='R.bg_percent_ceiling' />
    <do> $R.bg_percent_ceiling</do>
  </map>
  <map name='x' >
    <in col='R.x' />
    <do> $R.x</do>
  </map>
  <map name='y' >
    <in col='R.y' />
    <do> $R.y</do>
  </map>
  <map name='area' >
    <in col='R.area' />
    <do> $R.area</do>
  </map>
  <map name='flag' >
    <in col='R.flag' />
    <do> $R.flag</do>
  </map>
  <map name='mad' >
    <in col='R.mad' />
    <do> $R.mad</do>
  </map>
  <map name='percent_removed' >
    <in col='R.percent_removed' />
    <do> $R.percent_removed</do>
  </map>
  <map name='percent_replaced' >
    <in col='R.replaced' />
    <do> $R.replaced</do>
  </map>
   <map name='foreground' >
    <in col='G.foreground' />
    <do> $G.foreground </do>
  </map>
  <map name='background' >
    <in col='G.bkgd' />
    <do> $G.bkgd </do>
  </map>
  <map name='sd' >
    <in col='G.sd' />
    <do> $G.sd</do>
  </map>
  <map name='signal_to_noise' >
    <in col='G.sn' />
    <do> $G.sn</do>
  </map>
  <map name='percent_at_floor' >
    <in col='G.percent_floor' />
    <do> $G.percent_floor</do>
  </map>
  <map name='percent_at_ceiling' >
    <in col='G.percent_ceiling' />
    <do> $G.percent_ceiling</do>
  </map>
  <map name='bkg_percent_at_floor' >
    <in col='G.bg_percent_floor' />
    <do> $G.bg_percent_floor</do>
  </map>
  <map name='bg_percent_at_ceiling' >
    <in col='G.bg_percent_ceiling' />
    <do> $G.bg_percent_ceiling</do>
  </map>
  <map name='x' >
    <in col='G.x' />
    <do> $G.x</do>
  </map>
  <map name='y' >
    <in col='G.y' />
    <do> $G.y</do>
  </map>
  <map name='area' >
    <in col='G.area' />
    <do> $G.area</do>
  </map>
  <map name='flag' >
    <in col='G.flag' />
    <do> $G.flag</do>
  </map>
  <map name='mad' >
    <in col='G.mad' />
    <do> $G.mad</do>
  </map>
  <map name='percent_removed' >
    <in col='G.percent_removed' />
    <do> $G.percent_removed</do>
  </map>
  <map name='percent_replaced' >
    <in col='G.replaced' />
    <do> $G.replaced</do>
  </map>
</output>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_LoadBatchArrayResults_ArrayVision2.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- 
 $Revision$ $Date$ $Author$
-->

<cfg>
 <inputs qualifier_row_present='1' > 
  <header>
    <col name='R.foreground' header_val='Dens - Levels' qualifier='0' req='1' />
    <col name='R.sd' header_val='SD - Levels' qualifier='0' req='0' />
    <col name='R.x' header_val='PosX - mm' qualifier='0' req='0' />
    <col name='R.y' header_val='PosY - mm' qualifier='0' req='0' />
    <col name='R.area' header_val='Area - mm2' qualifier='0' req='0' />
    <col name='R.bkgd' header_val='Bkgd' qualifier='0' req='0' />
    <col name='R.sn' header_val='S/N' qualifier='0' req='0' />
    <col name='R.flag' header_val='Flag' qualifier='0' req='0' />
    <col name='R.percent_floor' header_val='% At Floor' qualifier='0' req='0' />
    <col name='R.percent_ceiling' header_val='% At Ceiling' qualifier='0' req='0' />
    <col name='R.bg_percent_floor' header_val='% At Floor - Bkgd' qualifier='0' req='0' />
    <col name='R.bg_percent_ceiling' header_val='% At Ceiling - Bkgd' qualifier='0' req='0' />
    <col name='R.mad' header_val='MAD' qualifier='0' req='0' />
    <col name='R.percent_removed' header_val='% Removed' qualifier='0' req='0' />
    <col name='R.percent_replaced' header_val='% Replaced' qualifier='0' req='0' />
    <col name='G.foreground' header_val='Dens - Levels' qualifier='1' req='1' />
    <col name='G.sd' header_val='SD - Levels' qualifier='1' req='0' />
    <col name='G.x' header_val='PosX - mm' qualifier='1' req='0' />
    <col name='G.y' header_val='PosY - mm' qualifier='1' req='0' />
    <col name='G.area' header_val='Area - mm2' qualifier='1' req='0' />
    <col name='G.bkgd' header_val='Bkgd' qualifier='1' req='0' />
    <col name='G.sn' header_val='S/N' qualifier='1' req='0' />
    <col name='G.flag' header_val='Flag' qualifier='1' req='0' />
    <col name='G.percent_floor' header_val='% At Floor' qualifier='1' req='0' />
    <col name='G.percent_ceiling' header_val='% At Ceiling' qualifier='1' req='0' />
    <col name='G.bg_percent_floor' header_val='% At Floor - Bkgd' qualifier='1' req='0' />
    <col name='G.bg_percent_ceiling' header_val='% At Ceiling - Bkgd' qualifier='1' req='0' />
    <col name='G.mad' header_val='MAD' qualifier='1' req='0' />
    <col name='G.percent_removed' header_val='% Removed' qualifier='1' req='0' />
    <col name='G.percent_replaced' header_val='% Replaced' qualifier='1' req='0' />
  </header>
 </inputs>

 <outputs>
  <map name='coordinate' >
    <in name='coor' />
    <do> $coor </do>
  </map>   
  <map name='foreground' >
    <in name='R.foreground' />
    <do> $R.foreground </do>
  </map>
  <map name='background' >
    <in name='R.bkgd' />
    <do> $R.bkgd </do>
  </map>
  <map name='sd' >
    <in name='R.sd' />
    <do> $R.sd</do>
  </map>
  <map name='signal_to_noise' >
    <in name='R.sn' />
    <do> $R.sn</do>
  </map>
  <map name='percent_at_floor' >
    <in name='R.percent_floor' />
    <do> $R.percent_floor</do>
  </map>
  <map name='percent_at_ceiling' >
    <in name='R.percent_ceiling' />
    <do> $R.percent_ceiling</do>
  </map>
  <map name='bkg_percent_at_floor' >
    <in name='R.bg_percent_floor' />
    <do> $R.bg_percent_floor</do>
  </map>
  <map name='bg_percent_at_ceiling' >
    <in name='R.bg_percent_ceiling' />
    <do> $R.bg_percent_ceiling</do>
  </map>
  <map name='x' >
    <in name='R.x' />
    <do> $R.x</do>
  </map>
  <map name='y' >
    <in name='R.y' />
    <do> $R.y</do>
  </map>
  <map name='area' >
    <in name='R.area' />
    <do> $R.area</do>
  </map>
  <map name='flag' >
    <in name='R.flag' />
    <do> $R.flag</do>
  </map>
  <map name='mad' >
    <in name='R.mad' />
    <do> $R.mad</do>
  </map>
  <map name='percent_removed' >
    <in name='R.percent_removed' />
    <do> $R.percent_removed</do>
  </map>
  <map name='percent_replaced' >
    <in name='R.replaced' />
    <do> $R.replaced</do>
  </map>
   <map name='foreground' >
    <in name='G.foreground' />
    <do> $G.foreground </do>
  </map>
  <map name='background' >
    <in name='G.bkgd' />
    <do> $G.bkgd </do>
  </map>
  <map name='sd' >
    <in name='G.sd' />
    <do> $G.sd</do>
  </map>
  <map name='signal_to_noise' >
    <in name='G.sn' />
    <do> $G.sn</do>
  </map>
  <map name='percent_at_floor' >
    <in name='G.percent_floor' />
    <do> $G.percent_floor</do>
  </map>
  <map name='percent_at_ceiling' >
    <in name='G.percent_ceiling' />
    <do> $G.percent_ceiling</do>
  </map>
  <map name='bkg_percent_at_floor' >
    <in name='G.bg_percent_floor' />
    <do> $G.bg_percent_floor</do>
  </map>
  <map name='bg_percent_at_ceiling' >
    <in name='G.bg_percent_ceiling' />
    <do> $G.bg_percent_ceiling</do>
  </map>
  <map name='x' >
    <in name='G.x' />
    <do> $G.x</do>
  </map>
  <map name='y' >
    <in name='G.y' />
    <do> $G.y</do>
  </map>
  <map name='area' >
    <in name='G.area' />
    <do> $G.area</do>
  </map>
  <map name='flag' >
    <in name='G.flag' />
    <do> $G.flag</do>
  </map>
  <map name='mad' >
    <in name='G.mad' />
    <do> $G.mad</do>
  </map>
  <map name='percent_removed' >
    <in name='G.percent_removed' />
    <do> $G.percent_removed</do>
  </map>
  <map name='percent_replaced' >
    <in name='G.replaced' />
    <do> $G.replaced</do>
  </map>
</output>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_BatchResultLoader_ArrayVision1.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- 
 $Revision$ $Date$ $Author$
-->

<cfg functions_class='GUS::Community::FileTranslator::Functions'>
 <inputs qualifier_row_present='1' > 
  <header >
    <col name='coordinate' header_val='Spot Labels' qualifier='0' req='1' />
    <col name='foreground' header_val='Dens - Levels' qualifier='0' req='1' />
    <col name='sd' header_val='SD - Levels' qualifier='0' req='0' />
    <col name='x' header_val='PosX - mm' qualifier='0' req='0' />
    <col name='y' header_val='PosY - mm' qualifier='0' req='0' />
    <col name='area' header_val='Area - mm2' qualifier='0' req='0' />
    <col name='bkgd' header_val='Bkgd' qualifier='0' req='0' />
    <col name='sn' header_val='S/N' qualifier='0' req='0' />
    <col name='flag' header_val='Flag' qualifier='0' req='0' />
    <col name='percent_floor' header_val='% At Floor' qualifier='0' req='0' />
    <col name='percent_ceiling' header_val='% At Ceiling' qualifier='0' req='0' />
    <col name='bg_percent_floor' header_val='% At Floor - Bkgd' qualifier='0' req='0' />
    <col name='bg_percent_ceiling' header_val='% At Ceiling - Bkgd' qualifier='0' req='0' />
    <col name='mad' header_val='MAD' qualifier='0' req='0' />
    <col name='percent_removed' header_val='% Removed' qualifier='0' req='0' />
    <col name='percent_replaced' header_val='% Replaced' qualifier='0' req='0' />
  </header>
 </inputs>
 <outputs>
    <idmap function='coordGenePix2RAD'
           output_header="array_row\tarray_column\tgrid_row\tgrid_column\tsub_row\tsub_column"
           mapkey='$coordinate'  >
      <in name='coordinate'/>
    </idmap>
  <map name='foreground' >
    <in name='foreground' />
    <do> $foreground </do>
  </map>
  <map name='background' >
    <in name='bkgd' />
    <do> $bkgd </do>
  </map>
  <map name='sd' >
    <in name='sd' />
    <do> $sd</do>
  </map>
  <map name='signal_to_noise' >
    <in name='sn' />
    <do> $sn</do>
  </map>
  <map name='percent_at_floor' >
    <in name='percent_floor' />
    <do> $percent_floor</do>
  </map>
  <map name='percent_at_ceiling' >
    <in name='percent_ceiling' />
    <do> $percent_ceiling</do>
  </map>
  <map name='bkg_percent_at_floor' >
    <in name='bg_percent_floor' />
    <do> $bg_percent_floor</do>
  </map>
  <map name='bg_percent_at_ceiling' >
    <in name='bg_percent_ceiling' />
    <do> $bg_percent_ceiling</do>
  </map>
  <map name='x' >
    <in name='x' />
    <do> $x</do>
  </map>
  <map name='y' >
    <in name='y' />
    <do> $y</do>
  </map>
  <map name='area' >
    <in name='area' />
    <do> $area</do>
  </map>
  <map name='flag' >
    <in name='flag' />
    <do> $flag</do>
  </map>
  <map name='mad' >
    <in name='mad' />
    <do> $mad</do>
  </map>
  <map name='percent_removed' >
    <in name='percent_removed' />
    <do> $percent_removed</do>
  </map>
  <map name='percent_replaced' >
    <in name='percent_replaced' />
    <do> $replaced</do>
  </map>  
</outputs>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_BatchResultLoader_AffymetrixMAS5.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- $Revision$ $Date$ $Author$ -->

<cfg>
  <inputs qualifier_row_present='0'>
    <header>
      <col header_val = 'Probe Set Name' req='1' name='probe_set_name' />
      <col header_val='Stat Pairs'  name='stat_pairs' />
      <col header_val='Stat Pairs Used'  name='stat_pairs_used' />
      <col header_val='Signal'  req='1' name='signal' />
      <col header_val='Detection'  req='1'  name='detection' />
      <col header_val='Detection p-value'  req='1' name='detection_p_value' />
    </header>
  </inputs>

  <outputs>
    <map name='name'>
      <in name='probe_set_name' />
      <do> $probe_set_name </do>
    </map>
    <map name='stat_pairs'>
      <in name='stat_pairs' />
      <do> $stat_pairs </do>
    </map>
    <map name='stat_pairs_used'>
      <in name='stat_pairs_used' />
      <do> $stat_pairs_used </do>
    </map>
    <map name='signal'>
      <in name='signal' />
      <do> $signal </do>
    </map>
    <map name='detection'>
      <in name='detection' />
      <do> $detection </do>
    </map>
    <map name='detection_p_value'>
      <in name='detection_p_value' />
      <do> $detection_p_value </do>
    </map>
  </outputs>
</cfg>

=== EuPathDB-Infra/GusAppFramework/Community/config/sample_LoadBatchArrayResults_RMAExpress.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!DOCTYPE cfg SYSTEM "FileTranslatorCfg.dtd" >

<!-- $Revision$ $Date$ $Author$ -->

<cfg>
  <inputs qualifier_row_present='0'>
    <header type="header" name='col_headers'>
      <col header_val = 'Probesets' req='1' name='probe_set_name' />
      <col header_val='file.CEL'  req = '1' name='value' />
    </header>
  </inputs>

  <outputs>
    <map name='name'>
      <in name='probe_set_name' />
      <do> $probe_set_name </do>
    </map>
    <map name='rma_expression_measure'>
      <in name='value' />
      <do> $value </do>
    </map>
  </outputs>
</cfg>
